PROMPT Criando modelo relacional Clyvo Vet / PortalWeb

CREATE TABLE t_aluno (
    rm_aluno       VARCHAR2(7)    NOT NULL,
    nm_aluno       VARCHAR2(80)   NOT NULL,
    dt_nascimento  DATE,
    CONSTRAINT pk_t_aluno PRIMARY KEY (rm_aluno)
);

CREATE TABLE t_tutor (
    id_tutor     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nm_tutor     VARCHAR2(120) NOT NULL,
    ds_email     VARCHAR2(120) NOT NULL,
    nr_telefone  VARCHAR2(20)  NOT NULL,
    CONSTRAINT pk_t_tutor PRIMARY KEY (id_tutor),
    CONSTRAINT uk_t_tutor_email UNIQUE (ds_email)
);

CREATE TABLE t_pet (
    id_pet         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nm_pet         VARCHAR2(80) NOT NULL,
    ds_especie     VARCHAR2(40) NOT NULL,
    ds_raca        VARCHAR2(60),
    dt_nascimento  DATE,
    vl_peso_kg     NUMBER(6,2),
    id_tutor       NUMBER NOT NULL,
    CONSTRAINT pk_t_pet PRIMARY KEY (id_pet),
    CONSTRAINT fk_t_pet_tutor FOREIGN KEY (id_tutor) REFERENCES t_tutor (id_tutor),
    CONSTRAINT ck_t_pet_peso CHECK (vl_peso_kg IS NULL OR vl_peso_kg > 0)
);

CREATE TABLE t_plano_cuidado (
    id_plano_cuidado  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pet            NUMBER NOT NULL,
    ds_titulo         VARCHAR2(120) NOT NULL,
    tp_categoria      VARCHAR2(30) NOT NULL,
    st_cuidado        VARCHAR2(30) DEFAULT 'PENDENTE' NOT NULL,
    dt_prevista       DATE NOT NULL,
    ds_observacao     VARCHAR2(500),
    CONSTRAINT pk_t_plano_cuidado PRIMARY KEY (id_plano_cuidado),
    CONSTRAINT fk_t_plano_pet FOREIGN KEY (id_pet) REFERENCES t_pet (id_pet),
    CONSTRAINT ck_t_plano_categoria CHECK (tp_categoria IN ('VACINA', 'CHECKUP', 'MEDICACAO', 'EXAME', 'RETORNO', 'ALERTA_RISCO')),
    CONSTRAINT ck_t_plano_status CHECK (st_cuidado IN ('PENDENTE', 'AGENDADO', 'CONCLUIDO', 'CANCELADO', 'ATRASADO'))
);

CREATE TABLE t_log_erro (
    id_log          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nm_procedure    VARCHAR2(120) NOT NULL,
    nm_usuario      VARCHAR2(120) NOT NULL,
    dt_ocorrencia   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    cd_erro         NUMBER,
    ds_erro         VARCHAR2(4000),
    CONSTRAINT pk_t_log_erro PRIMARY KEY (id_log)
);

CREATE INDEX ix_t_pet_tutor ON t_pet (id_tutor);
CREATE INDEX ix_t_plano_pet ON t_plano_cuidado (id_pet);
CREATE INDEX ix_t_plano_status ON t_plano_cuidado (st_cuidado);
